use dandelion_commons::{
    err_dandelion, records::Recorder, DandelionError, DandelionResult, MultinodeError,
};
use machine_interface::composition::{CompositionSet, LocalCompositionSet};
use prost::{
    bytes::{Buf, Bytes},
    Message,
};
use tokio::sync::oneshot;

pub mod client;
pub mod config;
pub mod data;
mod util;

// TODO remove when runtime is unified, and await dispatcher directly
pub enum DispatcherCommand {
    FunctionRegistration {
        name: String,
        engine_type: machine_interface::machine_config::EngineType,
        context_size: usize,
        path: String,
        metadata: machine_interface::function_driver::Metadata,
        callback: oneshot::Sender<DandelionResult<()>>,
    },
    CompositionRegistration {
        composition: String,
        callback: oneshot::Sender<DandelionResult<()>>,
    },
    FunctionRequest {
        function_id: std::sync::Arc<String>,
        // Todo: check if we still need this for caching, otherwise, remiove and unify with temote request
        inputs: Vec<Option<CompositionSet>>,
        is_cold: bool,
        recorder: Recorder,
        callback: oneshot::Sender<DandelionResult<(Vec<Option<LocalCompositionSet>>, Recorder)>>,
    },
    RemoteFunctionRequest {
        function_id: std::sync::Arc<String>,
        inputs: Vec<Option<CompositionSet>>,
        is_cold: bool,
        recorder: Recorder,
        callback: crate::client::ResultCallback,
    },
    CompositionRequest {
        composition: String,
        inputs: Vec<Option<CompositionSet>>,
        is_cold: bool,
        recorder: Recorder,
        callback: oneshot::Sender<DandelionResult<(Vec<Option<LocalCompositionSet>>, Recorder)>>,
    },
}

// include autogenerated protobufs
mod proto {
    include!(concat!(env!("OUT_DIR"), "/multinode_proto.rs"));
}

// serialization

macro_rules! serialize {
    ($proto_msg:ident) => {{
        let mut buf = Vec::with_capacity($proto_msg.encoded_len());
        $proto_msg.encode(&mut buf).unwrap();
        prost::bytes::Bytes::from(buf)
    }};
}

fn serialize_node_info(node_info: proto::NodeInfo) -> Bytes {
    serialize!(node_info)
}

fn serialize_remote_message(worker_message: proto::RemoteMessage) -> Bytes {
    serialize!(worker_message)
}

fn serialize_queue_message(queue_message: proto::QueueMessage) -> Bytes {
    serialize!(queue_message)
}

fn deserialize_node_info(buf: impl Buf) -> DandelionResult<proto::NodeInfo> {
    match proto::NodeInfo::decode(buf) {
        Ok(node_info) => Ok(node_info),
        Err(err) => err_dandelion!(DandelionError::Multinode(
            MultinodeError::DeserializationError(format!("{:?}", err)),
        )),
    }
}

fn deserialize_remote_message(buf: Bytes) -> DandelionResult<proto::RemoteMessage> {
    match proto::RemoteMessage::decode(buf) {
        Ok(resp) => Ok(resp),
        Err(err) => err_dandelion!(DandelionError::Multinode(
            MultinodeError::DeserializationError(format!("{:?}", err)),
        )),
    }
}

fn deserialize_queue_message(buf: Bytes) -> DandelionResult<proto::QueueMessage> {
    match proto::QueueMessage::decode(buf) {
        Ok(message) => Ok(message),
        Err(err) => err_dandelion!(DandelionError::Multinode(
            MultinodeError::DeserializationError(format!("{:?}", err)),
        )),
    }
}

#[test]
fn test_serialize_invocation_request() {
    use crate::proto::{item_data, queue_message, Invocation, QueueMessage};
    use machine_interface::{composition::ItemData, memory_domain::ContextTrait};

    // construct invocation data
    let expected_id = String::from("TestName");
    let item_0_0_name = "a";
    let item_0_0_data = 123u64;
    let item_1_0_name = "b";
    let item_1_0_data = 987u64;
    let item_1_1_name = "c";
    let item_1_1_data = 123u128 | (456u128 << 64);
    let mut data = vec![];
    data.extend_from_slice(&item_0_0_data.to_le_bytes());
    data.extend_from_slice(&item_1_0_data.to_le_bytes());
    data.extend_from_slice(&item_1_1_data.to_le_bytes());
    let mut in_context =
        machine_interface::memory_domain::read_only::ReadOnlyContext::new(data.into_boxed_slice())
            .expect("Should be able to create read only context");
    in_context.content = vec![
        Some(machine_interface::DataSet {
            ident: String::from("Set 0"),
            buffers: vec![machine_interface::DataItem {
                ident: String::from(item_0_0_name),
                data: machine_interface::Position {
                    offset: 0,
                    size: size_of::<u64>(),
                },
                key: 0,
            }],
        }),
        Some(machine_interface::DataSet {
            ident: String::from("Set 1"),
            buffers: vec![
                machine_interface::DataItem {
                    ident: String::from(item_1_0_name),
                    data: machine_interface::Position {
                        offset: size_of::<u64>(),
                        size: size_of::<u64>(),
                    },
                    key: 7,
                },
                machine_interface::DataItem {
                    ident: String::from(item_1_1_name),
                    data: machine_interface::Position {
                        offset: 2 * size_of::<u64>(),
                        size: size_of::<u128>(),
                    },
                    key: 14,
                },
            ],
        }),
    ];
    let inputs = machine_interface::composition::CompositionSet::from_context(in_context);

    // serialize
    let node_id = 42;
    let mut next_data_id = 0;
    let serialized_metadata_sets = util::composition_sets_to_proto(inputs, |item, context| {
        let data_id = next_data_id;
        next_data_id += 1;
        let data_slice = context
            .get_chunk_ref(item.data.offset, item.data.size)
            .unwrap();
        match data_id {
            0 => assert_eq!(&item_0_0_data.to_le_bytes(), data_slice),
            1 => assert_eq!(&item_1_0_data.to_le_bytes(), data_slice),
            2 => assert_eq!(&item_1_1_data.to_le_bytes(), data_slice),
            _ => panic!("Unexpected exported data id"),
        }
        machine_interface::composition::RemoteData::new(node_id, data_id)
    });
    // assert!(set_option.is_none());
    assert_eq!(3, next_data_id);
    println!("serialized set: {:?}", serialized_metadata_sets);
    // not checking set names, as they are set arbitrarily, since they are ignored anyway
    // check the items
    assert_eq!(2, serialized_metadata_sets.len());

    assert_eq!(1, serialized_metadata_sets[0].items.len());
    assert_eq!(item_0_0_name, serialized_metadata_sets[0].items[0].ident);
    assert_eq!(0, serialized_metadata_sets[0].items[0].key);
    assert_eq!(
        item_data::Data::RemoteData(proto::RemoteData {
            node_id,
            data_id: 0,
            size: size_of_val(&item_0_0_data) as u64,
        }),
        serialized_metadata_sets[0].items[0]
            .data
            .clone()
            .unwrap()
            .data
            .unwrap()
    );

    assert_eq!(2, serialized_metadata_sets[1].items.len());
    assert_eq!(item_1_0_name, serialized_metadata_sets[1].items[0].ident);
    assert_eq!(7, serialized_metadata_sets[1].items[0].key);
    assert_eq!(
        item_data::Data::RemoteData(proto::RemoteData {
            node_id,
            data_id: 1,
            size: size_of_val(&item_1_0_data) as u64,
        }),
        serialized_metadata_sets[1].items[0]
            .data
            .clone()
            .unwrap()
            .data
            .unwrap()
    );
    assert_eq!(item_1_1_name, serialized_metadata_sets[1].items[1].ident);
    assert_eq!(14, serialized_metadata_sets[1].items[1].key);
    assert_eq!(
        item_data::Data::RemoteData(proto::RemoteData {
            node_id,
            data_id: 2,
            size: size_of_val(&item_1_1_data) as u64,
        }),
        serialized_metadata_sets[1].items[1]
            .data
            .clone()
            .unwrap()
            .data
            .unwrap()
    );

    let request = QueueMessage {
        queue_message: Some(proto::queue_message::QueueMessage::Invocations(
            proto::RepeatedInvocations {
                invocations: vec![crate::proto::Invocation {
                    function_id: expected_id.clone(),
                    metadata_sets: serialized_metadata_sets.clone(),
                    invocation_id: 7,
                    caching: true,
                }],
            },
        )),
    };
    let bytes = serialize_queue_message(request);
    let invocation = bytes.clone();

    // deserialize
    let message = deserialize_queue_message(invocation)
        .unwrap()
        .queue_message
        .unwrap();
    let Invocation {
        invocation_id,
        function_id: deserialized_id,
        metadata_sets: deserialized_metadata_sets,
        caching,
    } = if let queue_message::QueueMessage::Invocations(proto::RepeatedInvocations {
        invocations,
    }) = message
    {
        assert_eq!(1, invocations.len());
        invocations[0].clone()
    } else {
        panic!("Should have deserialized an invocation");
    };
    assert_eq!(expected_id, deserialized_id);
    assert_eq!(serialized_metadata_sets, deserialized_metadata_sets);
    assert_eq!(invocation_id, 7);
    assert!(caching);

    // check the composition sets are as expected
    let mut sets = util::proto_data_sets_to_composition_sets(deserialized_metadata_sets, None);
    assert_eq!(2, sets.len());

    let set_0 = sets[0].take().expect("Should have Some(_) for set 0");
    assert_eq!(1, set_0.len());
    let (item_0_0, item_0_0_item_data) = set_0.into_iter().next().unwrap();
    assert_eq!(item_0_0_name, item_0_0.ident);
    assert_eq!(0, item_0_0.key);
    assert_eq!(0, item_0_0.data.offset);
    assert_eq!(size_of_val(&item_0_0_data), item_0_0.data.size);
    match item_0_0_item_data {
        ItemData::RemoteData(remote_data) => {
            assert_eq!(node_id, remote_data.node_id);
            assert_eq!(0, remote_data.data_id);
        }
        _ => panic!("Should have remote data"),
    };

    let set_1 = sets[1].take().expect("Should have Some(_) for set 1");
    assert_eq!(2, set_1.len());
    let mut set_1_iterator = set_1.into_iter();
    let (item_1_0, item_1_0_item_data) = set_1_iterator.next().unwrap();
    assert_eq!(item_1_0_name, item_1_0.ident);
    assert_eq!(7, item_1_0.key);
    assert_eq!(0, item_1_0.data.offset);
    assert_eq!(size_of_val(&item_1_0_data), item_1_0.data.size);
    match item_1_0_item_data {
        ItemData::RemoteData(remote_data) => {
            assert_eq!(node_id, remote_data.node_id);
            assert_eq!(1, remote_data.data_id);
        }
        _ => panic!("Should have remote data"),
    };
    let (item_1_1, item_1_1_item_data) = set_1_iterator.next().unwrap();
    assert_eq!(item_1_1_name, item_1_1.ident);
    assert_eq!(14, item_1_1.key);
    assert_eq!(0, item_1_1.data.offset);
    assert_eq!(size_of_val(&item_1_1_data), item_1_1.data.size);
    match item_1_1_item_data {
        ItemData::RemoteData(remote_data) => {
            assert_eq!(node_id, remote_data.node_id);
            assert_eq!(2, remote_data.data_id);
        }
        _ => panic!("Should have remote data"),
    };
}
