name: Dandelion Clippy Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # set to fail fast to false so all combinations are tested
    strategy:
      fail-fast: false
      # test different available compute engines with different system engines
      matrix:
        compute_driver: [ mmu, kvm ]
        additional_features: ["timestamp", "log_function_stdio", "blocking_queue", "data_locality"]

    name: ${{matrix.compute_driver}} - ${{ matrix.additional_features }}
    runs-on: ubuntu-latest

    steps:
    # check out the code
    - uses: actions/checkout@v3
    # install protobuff to be able to build the workspace
    - name: setup protobuf
      run: |
        sudo apt-get update
        sudo apt-get install protobuf-compiler
    # run the actual checks
    - name: run tests
      run: cargo clippy --all-targets -F ${{matrix.compute_driver}},${{matrix.additional_features}}
