name: Dandelion depenency checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # check out the code
    - uses: actions/checkout@v3
    - name: install cargo machete
      run: |
        cargo install cargo-machete
        cargo-machete
