name: Dandelion Cargo Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # check out the code
    - uses: actions/checkout@v3
    - name: cargo fmt check
      run: cargo fmt --all -- --check
